// server/src/agents/decisionAdvisorAgent.js
import { logger } from '../utils/logger.js';

/**
 * Advises on strategic decisions based on provided business insights using an LLM.
 * Designed to dynamically generate recommendations based on any type of insight.
 *
 * @param {function(string, object): Promise<any>} callLLM - The function to call the LLM (e.g., callLLM from llmClient.js).
 * @param {Array<object>} insights - An array of insight objects generated by the Insight Generator (can have dynamic types).
 * @param {object} aiSettings - AI configuration settings (provider, model, temperature, maxTokens).
 * @returns {Promise<Array<object>>} A promise that resolves to an array of decision recommendation objects.
 */
export async function adviseOnDecisions(callLLM, insights, aiSettings = {}) {
    logger.info('[DecisionAdvisorAgent] Advising on decisions based on insights...');

    if (!Array.isArray(insights) || insights.length === 0) {
        logger.warn('[DecisionAdvisorAgent] No insights provided to generate decisions.');
        return [];
    }

    const insightsText = insights
        .map(i => `- Type: ${i.type}\n  Title: ${i.title}\n  Description: ${i.description}${i.data ? `\n  Data: ${JSON.stringify(i.data)}` : ''}`)
        .join('\n\n');

    const prompt = `You are an AI Decision Advisor. Your role is to analyze the provided detailed business insights and recommend actionable strategic decisions.

**Instructions:**
1.  **Translate Insights into Actions:** For each insight, propose one or more concrete, actionable decisions that a business can take.
2.  **Specificity:** Decisions should be specific enough to guide next steps, even if they require further detailed planning.
3.  **Rationale:** Provide a clear rationale for each decision, directly linking it to the specific insight(s) it addresses.
4.  **Urgency:** Assign an urgency level (High, Medium, Low) based on the potential impact and time sensitivity of the decision.
5.  **Category:** Categorize each decision into a relevant business function (e.g., "Sales", "Marketing", "Operations", "Product Development", "Inventory", "Finance", "Customer Relations", "Risk Management"). This should align with practical business departments.
6.  **Output Format:** Provide decisions as a JSON array of objects. Each object must have the following structure:
    * \`title\`: (string) A concise title for the decision (e.g., "Launch Targeted Marketing Campaign").
    * \`recommendation\`: (string) The detailed recommendation for action.
    * \`rationale\`: (string) The reason behind the recommendation, linked to the insights.
    * \`urgency\`: (string) "High", "Medium", or "Low".
    * \`category\`: (string) The business area the decision falls under (e.g., "sales", "marketing", "operations", "product_development", "inventory", "finance", "customer_relations", "risk_management", "process_improvement").

**Example Desired Output (JSON array):**
\`\`\`json
[
  {
    "title": "Investigate Product B Stagnation",
    "recommendation": "Conduct a comprehensive market analysis and customer feedback survey for Product Category B to understand the reasons for sales stagnation. Evaluate competitive offerings and consider a product refresh or adjusted pricing strategy.",
    "rationale": "The 'Monthly Revenue Growth Analysis' insight indicates stagnation in Product Category B, suggesting a need for deeper understanding to prevent future revenue loss.",
    "urgency": "High",
    "category": "product_development"
  },
  {
    "title": "Increase Marketing Spend for Top Products",
    "recommendation": "Allocate additional marketing budget towards digital campaigns and promotional offers for products X, Y, and Z, which have been identified as top revenue drivers. Focus on channels with high ROI.",
    "rationale": "The 'Top 5 Performing Products by Revenue' insight shows these products are critical. Capitalizing on their current momentum with increased marketing can further boost overall revenue.",
    "urgency": "Medium",
    "category": "marketing"
  },
  {
    "title": "Immediate Investigation of South Region Returns",
    "recommendation": "Initiate an urgent investigation into the supply chain, logistics, and quality control processes specifically for electronic goods distributed to the 'South' region. Temporarily pause shipments of affected product lines to this region if necessary until the root cause is identified and resolved.",
    "rationale": "The 'Unusual Spike in Returns for Region South' insight highlights a critical issue that could lead to significant financial losses and customer dissatisfaction if not addressed immediately.",
    "urgency": "High",
    "category": "operations"
  }
]
\`\`\`

**Here are the business insights generated for your review:**
${insightsText}

Your entire response must be the JSON array, with no additional text.
`;

    try {
        const decisions = await callLLM(prompt, aiSettings);

        const validate = d =>
            typeof d === 'object' &&
            typeof d.title === 'string' &&
            typeof d.recommendation === 'string' &&
            typeof d.rationale === 'string' &&
            typeof d.urgency === 'string' &&
            typeof d.category === 'string';

        let resultArray = [];

        if (Array.isArray(decisions)) {
            resultArray = decisions;
        } else if (typeof decisions === 'object' && decisions !== null) {
            resultArray = Object.values(decisions);
        }

        const valid = resultArray.filter(validate);

        if (valid.length > 0) {
            logger.info('[DecisionAdvisorAgent] Successfully generated decisions:', valid);
            return valid;
        }

        logger.error('[DecisionAdvisorAgent] LLM response did not match expected format or was empty:', decisions);
        return [];
    } catch (error) {
        logger.error('[DecisionAdvisorAgent] Error advising on decisions from LLM:', error);
        throw new Error(`Failed to advise on decisions: ${error.message}`);
    }
}